package constant

const (
	CMD_PING      = "PING"
	CMD_GET       = "GET"
	CMD_SET       = "SET"
	CMD_TTL       = "TTL"
	CMD_PTTL      = "PTTL"
	CMD_DEL       = "DEL"
	CMD_EXIST     = "EXISTS"
	CMD_EXPIRE    = "EXPIRE"
	CMD_SADD      = "SADD"
	CMD_SREM      = "SREM"
	CMD_SISMEMBER = "SISMEMBER"
	CMD_SMEMBERS  = "SMEMBERS"
	CMD_ZADD      = "ZADD"
	CMD_ZSCORE    = "ZSCORE"
	CMD_ZRANK     = "ZRANK"
	CMD_ZREM      = "ZREM"
	CMD_INFO      = "INFO"
	// Count-Min Sketch
	CMD_CMS_INITBYDIM  = "CMS.INITBYDIM"
	CMD_CMS_INITBYPROB = "CMS.INITBYPROB"
	CMD_CMS_INCRBY     = "CMS.INCRBY"
	CMD_CMS_QUERY      = "CMS.QUERY"
	// Bloom filter
	CMD_BF_RESERVE = "BF.RESERVE"
	CMD_BF_ADD     = "BF.ADD"
	CMD_BF_MADD    = "BF.MADD"
	CMD_BF_EXISTS  = "BF.EXISTS"
	CMD_BF_MEXISTS = "BF.MEXISTS"
)
